<?php 
include 'db/init.php'; 

class Head 
{
	function dispHead($active){
		$output = '';		
		$output .= '<div class="header_container headerstyle-style3">';
		$output .= '	<div class="fullwidth_container style-top-bar">';
		$output .= '		<div class="container">';
		$output .= '			<div class="info_above_menu">';
		$output .= '				<div class="nine columns" style="float:left;top: 13px; position:relative;">';
		$output .= '					<div class="telephone">';
		$output .= '						<i class="fa fa-phone"></i>  +86-27-84658955 / 84658466';
		$output .= '					</div>		';							
		$output .= '					<div class="email">';
		$output .= '						<i class="fa fa-envelope"></i>';
		$output .= '						<a href="mailto:info@gn-laser.com ">info@gn-laser.com </a>';
		$output .= '					</div>			';				
		$output .= '					<div class="address">';
		$output .= '						<i class="fa fa-map-marker"></i> Quanli first road, Wuhan, China.';
		$output .= '					</div>';
		$output .= '				</div>	';
		$output .= '				<div class="seven columns">';																
		$output .= '					<div class="socialdiv" style="float:right;">';
		$output .= '						<ul>';
		$output .= '							<li><a href="https://www.facebook.com/GNLaser" target="_blank" class="facebook" title="Facebook"></a></li>	';							
		$output .= '							<li><a href="https://twitter.com/gn_laser" target="_blank" class="twitter" title="Twitter"></a></li>';
		$output .= '							<li><a href="https://www.youtube.com/user/GNlaser" target="_blank" class="youtube" title="Youtube"></a></li>';
		$output .= '							<li><a href="skype:gn.laser.china?chat"  class="skype" title="Skype"></a></li>';
		$output .= '						</ul>';
		$output .= '					</div>';
		$output .= '				</div>	';		
		$output .= '			</div>';
		$output .= '		</div>';
		$output .= '	</div>	';
		$output .= '	<header id="header" class="container">	';	
		$output .= '		<div class="logo_and_menu">	';
		$output .= '			<div class="logo columns">';
		$output .= '				<h1>';
		$output .= '					<a href="index.php" tabindex="-1">';
		$output .= '						<img class="logo_normal notalone" src="img/logo.png" alt="logo gnlaser" title="gnlaser logo">';				
		$output .= '			    		<img class="logo_retina" src="img/logo2x.png" alt="logo gnlaser retina" title="logo gnlaser retina">';
		$output .= '			    	</a>';
		$output .= '			    </h1>';
		$output .= '    	</div>';
		$output .= '		<nav id="menu" class="columns">		';													                    					
		$output .= '			<ul id="menulava" class="sf-menu">';
		$output .= '				<li '; if($active=='home'){$output.='class="current-menu-item"';}else{$output.='""';}$output.='><a href="index.php">Home</a></li>	';				
		$output .= '				<li '; if($active=='about'){$output.='class="current-menu-item"';}else{$output.='""';}$output.='><a href="about.php">About Us</a></li>';	
		$output .= '				<li '; if($active=='products'){$output.='class="current-menu-item"';}else{$output.='""';}$output.='><a href="products.php">Products</a>';
		$output .= '					<ul class="sub-menu">';
		$output .= '						<li class=""><a href="products.php?category=fiber">Fiber Laser Cutting Machine</a></li>	';							
		$output .= '						<li class=""><a href="products.php?category=yag">YAG Laser Cutting Machine</a></li>	';							
		$output .= '						<li class=""><a href="products.php?category=tube">Tube Laser Cutting Machine</a></li>	';							
		$output .= '					</ul>';
		$output .= '				</li>';
		$output .= '				<li '; if($active=='application'){$output.='class="current-menu-item"';}else{$output.='""';}$output.='><a href="#">Application</a>';
		$output .= '					<ul class="sub-menu">';
		$output .= '						<li class=""><a href="application.php">Applications</a></li>';
		$output .= '						<li class=""><a href="video.php">Video Display</a></li>	';							
		$output .= '					</ul>';
		$output .= '				</li>';
		$output .= '				<li '; if($active=='news'){$output.='class="current-menu-item"';}else{$output.='""';}$output.='><a href="news.php">News</a></li>';
		$output .= '				<li '; if($active=='service'){$output.='class="current-menu-item"';}else{$output.='""';}$output.='><a href="#">Service</a>';
		$output .= '					<ul class="sub-menu">';
		$output .= '						<li class=""><a href="service.php">Services</a></li>	';							
		$output .= '						<li class=""><a href="downloads.php">Downloads</a></li>	';							
		$output .= '					</ul>';
		$output .= '				</li>';
		$output .= '				<li '; if($active=='contact'){$output.='class="current-menu-item"';}else{$output.='""';}$output.='><a href="contact.php">Contact</a></li>';	
		$output .= '			</ul>		';			
		$output .= '			<div id="select-menu">';
		$output .= '				<select class="dropdown-menu" id="menu-primary-navigation">';
		$output .= '			        <option value="">';
		$output .= '			            Mobile menu';
		$output .= '			        </option>	';				
		$output .= '			        <option value="">';
		$output .= '			            &nbsp;';
		$output .= '			        </option>	';				
		$output .= '			        <option value="index.php">';
		$output .= '			            Home';
		$output .= '			        </option>';
		$output .= '			        <option value="">';
		$output .= '			            &nbsp;';
		$output .= '			        </option>		';			
		$output .= '			        <option value="about.php">';
		$output .= '			            About Us';
		$output .= '			        </option>';
		$output .= '			        <option value="">';
		$output .= '			            &nbsp;';
		$output .= '			        </option>			';		
		$output .= '			        <option value="products.php">';
		$output .= '			            Products';
		$output .= '			        </option>';
		$output .= '			        <option value="">';
		$output .= '			            &nbsp;';
		$output .= '			        </option>		';			
		$output .= '			        <option value="application.php">';
		$output .= '			            Applications';
		$output .= '			        </option>';				
		$output .= '			        <option value="video.php">';
		$output .= '			            Video';
		$output .= '			        </option>';
		$output .= '			        <option value="">';
		$output .= '			            &nbsp;';
		$output .= '			        </option>	';				
		$output .= '			        <option value="news.php">';
		$output .= '			            News';
		$output .= '			        </option>';
		$output .= '					<option value="">';
		$output .= '			            &nbsp;';
		$output .= '			        </option>';
		$output .= '			        <option value="service.php">';
		$output .= '			            Services';
		$output .= '			        </option>';				
		$output .= '			        <option value="downloads.php">';
		$output .= '			            Downloads';
		$output .= '			        </option>';
		$output .= '			        <option value="">';
		$output .= '			            &nbsp;';
		$output .= '			        </option>	';				
		$output .= '			        <option value="contact.php">';
		$output .= '			            Contacts';
		$output .= '			        </option>';
		$output .= '			    </select>';
		$output .= '			</div> ';
		$output .= '		</nav>	';									
		$output .= '	</div>';
		$output .= '	</header>';
		$output .= '	<div class="header-shadow"></div>';		
		$output .= '</div>';
		return $output;
	}
	function dispFoot(){
		$news = getData("SELECT * FROM `news` ORDER BY `news_id` DESC LIMIT 4");
		$nbN = count($news);
		$output = '';
		$output .= '<div id="big_footer">	';
	    $output .= '	<div id="footer_content">';
	    $output .= '		<div class="container">';
	    $output .= '			<div class="four columns">';
	    $output .= '				<h4>GNlaser</h4><hr/>';
	    $output .= '				<div class="textwidget">';
	    $output .= '					<img src="img/logo.png" height="98" width="298" alt="GNlaser logo"> <br/> <br/>';
		$output .= '					<div class="main_cols container">';
		$output .= '						<div class="eight-third column">';
		$output .= '							<div>';
		$output .= '								<div id="numerical-2893" class="numericals"> 	';									
		$output .= '									<script type="text/javascript"> ';
		$output .= '									    jQuery(window).load(function(){';
		$output .= '									    	if (isScrolledIntoView("numerical-1")){';
		$output .= '									    		jQuery(\'#numerical-1\').removeClass(\'notinview\');';
		$output .= '									    		incrementNumerical(\'#numerical-1\', 540, 5);';
		$output .= '									    	}';
		$output .= '									    });';
		$output .= '									    jQuery(window).scroll(function(){  ';  	
		$output .= '									    	if (jQuery(\'#numerical-1.notinview\').length){';
		$output .= '									    		if (isScrolledIntoView("numerical-1")){';
		$output .= '										    		jQuery(\'#numerical-1\').removeClass(\'notinview\');';
		$output .= '										    		incrementNumerical(\'#numerical-1\', 540, 5);';
		$output .= '									        	}';
		$output .= '									        }';
		$output .= '									    });';
		$output .= '							        </script> ';
		$output .= '							        ';
		$output .= '							        <div class="numerical-container"><div id="numerical-1" class="notinview">';
		$output .= '							        	<div style="font-size:40px; line-height: .5em;text-align: left;" class="value colored">0</div>';
		$output .= '							        		<div style="font-size:;" class="unit"></div>';
		$output .= '							        	</div>';
		$output .= '							        	<div class="numerical-content">Happy Clients</div>';
		$output .= '							        </div>';
		$output .= '							    </div>';
		$output .= '							</div>';
		$output .= '						</div>';
		$output .= '						<div class="eight-third column">';
		$output .= '							<div>';
		$output .= '								<div id="numerical-3510" class="numericals">';
		$output .= '									<script type="text/javascript"> ';
		$output .= '									    jQuery(window).load(function(){';
		$output .= '									    	if (isScrolledIntoView("numerical-2")){';
		$output .= '									    		jQuery(\'#numerical-2\').removeClass(\'notinview\');';
		$output .= '									    		incrementNumerical(\'#numerical-2\', 928, 1);';
		$output .= '									    	}';
		$output .= '									    });';
		$output .= '									    jQuery(window).scroll(function(){  ';  	
		$output .= '									    	if (jQuery(\'#numerical-2.notinview\').length){';
		$output .= '									    		if (isScrolledIntoView("numerical-2")){';
		$output .= '										    		jQuery(\'#numerical-2\').removeClass(\'notinview\');';
		$output .= '										    		incrementNumerical(\'#numerical-2\', 928, 1);';
		$output .= '									        	}';
		$output .= '									        }';
		$output .= '									    });';
		$output .= '							        </script>';
		$output .= '							        <div class="numerical-container">';
		$output .= '							        	<div id="numerical-2" class="notinview">';
		$output .= '							        		<div style="font-size:40px;line-height: .5em;text-align: left;" class="value colored">0</div>';
		$output .= '							        		<div style="font-size:;" class="unit"></div>';
		$output .= '							        	</div>';
		$output .= '							        <div class="numerical-content">Team members</div>';
		$output .= '							     </div>';
		$output .= '							 </div>';
		$output .= '						</div>';
		$output .= '					</div>';
		$output .= '				</div>';
		$output .= '			</div>	';			
		$output .= '		</div>';
		$output .= '		<div class="four columns">  ';  
		$output .= '		    <div class="twitter_container">';
		$output .= '				<div class="title">';
		$output .= '					<h4>About GNlaser</h4>';
		$output .= '				</div>';
		$output .= '				<div id="twitter_update_list">';
		$output .= '					<p> <a href="#">Wuhan GNlaser Equipment Manufacturing Co., Ltd.</a> specializes in the research, developping, producing and marketing of laser equipments. Over 10 years development, we have an integrative team of many hi-tech elites and experts in mechanism, optoelectronics industrial automation and software development.</p>';
		$output .= '				</div>';
		$output .= '			</div>';
		$output .= '		 </div>';
		$output .= '		 <div class="four columns">';
		$output .= '		 	<div id="recentPostsSidebar_widget">	';
		$output .= '				<h2>Latest News</h2>';						
		$output .= '				<ul class="recentposts_listing">';
		for ($i=0; $i < $nbN ; $i++) { 
			$output .= '					<li>';
			$output .= '						<div class="recentPostsSidebar slider"></div>';
			$output .= '						<div class="rc-container">';
			$output .= '						<script type="text/javascript" src="js/custom.js"></script>';
			$output .= '							<a class="the_title" onclick="nb_click(\''.$news[$i]['news_id'].'\',\''.$news[$i]['click'].'\')" href="news_more.php?id='.$news[$i]['news_id'].'" title="'.$news[$i]['title'].'">'.mb_substr($news[$i]['title'],0,27,'UTF-8').'[...]</a><br />';
			$output .= '							<div class="recent-contantbottom">';
			$output .= '								<span class="blog-i">by:&nbsp;</span><a class="the_author" href="#">'.$news[$i]['author'] .'</a>';
			$output .= '							</div>';
			$output .= '						</div>';
			$output .= '					</li>	';	
		}
		
		$output .= '				</ul>';
		$output .= '			</div>';
		$output .= '		</div>';
		$output .= '		<div class="four columns">';
		$output .= '			<h4>Contact details</h4><hr/>';
		$output .= '			<div class="textwidget">';
		$output .= '				No.4, 7th Part, Private Science and Technology Industrial Park, Quanli First Road, Economic and Technological Development Zone, Wuhan, China<br/><br>	';		
		$output .= '					<strong>Email:</strong> info@gn-laser.com<br/>';
		$output .= '					<strong>Phone:</strong> +86-27-84658955 / 84658466<br/>';
		$output .= '					<strong>Fax:</strong> +86-27-83600135<br/>';
		$output .= '					<strong>Skype:</strong> gn.laser.china<br/><br/>';							
		$output .= '			</div>';
		$output .= '		</div>';
		$output .= '	</div>';
	    $output .= '</div>';
	    $output .= '<div class="copys">';
		$output .= '	<div class="container">';
		$output .= '		<div class="copys_left eight columns">';
		$output .= '			Copyright © 2012 GNLASER | All Rights Reserved';
		$output .= '			<br/>';
		$output .= '			<a href="index.php">Home</a> - <a href="about.php">About Us</a> - <a href="products.php">Products</a> - <a href="#">Sitemap</a> ';
		$output .= '		</div>';
		$output .= '		<div class="copys_right eight columns">';
		$output .= '			<div class="footer_right_content">';
		$output .= '				<div class="socialdiv" style="float:right;">';
		$output .= '					<ul>';
		$output .= '						<li><a href="https://www.facebook.com/GNLaser" target="_blank" class="facebook" title="Facebook"></a></li>';
		$output .= '						<li><a href="https://twitter.com/gn_laser" target="_blank" class="twitter" title="Twitter"></a></li>';
		$output .= '						<li><a href="https://www.youtube.com/user/GNlaser" target="_blank" class="youtube" title="Youtube"></a></li>';
		$output .= '						<li><a href="skype:gn.laser.china?chat" target="_blank" class="skype" title="Skype"></a></li>	';							
		$output .= '					</ul>';
		$output .= '				</div>';
		$output .= '			</div>';
		$output .= '		</div>';
		$output .= '	</div>';
		$output .= '</div>';
		return $output;

	}
	function dispmeta(){
		$output = '';
		$output .= '<meta http-equiv="Content-Type" content="text/html; charset=utf-8">';
		$output .= '<meta content="width=device-width, initial-scale=1.0, maximum-scale=1" name="viewport">';
		$output .= '<link rel="shortcut icon" href="img/favicon.ico">';
		$output .= '<link rel="apple-touch-icon" href="#">';
		$output .= '<link rel="apple-touch-icon" sizes="72x72" href="#">';
		$output .= '<link rel="apple-touch-icon" sizes="114x114" href="#">';
		$output .= '<link rel="apple-touch-icon" sizes="144x144" href="#">	';
		$output .= '<link rel="stylesheet" href="css/style.css" type="text/css" media="all" />';
		$output .= '<link rel="stylesheet" href="css/skeleton.css" type="text/css" media="all" />';
		$output .= '<link rel="stylesheet" href="css/camera.css" type="text/css" media="all" />';
		$output .= '<link rel="stylesheet" href="css/tango/skin.css" type="text/css" media="all" />';
		$output .= '<link rel="stylesheet" href="css/flexslider.css" type="text/css" media="all" />';
		$output .= '<link rel="stylesheet" href="css/blog.css" type="text/css" media="all" />';
		$output .= '<link rel="stylesheet" href="css/prettyPhoto.css" type="text/css" media="all" />';
		$output .= '<link rel="stylesheet" href="css/resize.css" type="text/css" media="all" />';
		$output .= '<link rel="stylesheet" href="css/font-awesome.min.css" type="text/css" media="all" />';
		$output .= '<link rel="stylesheet" href="css/retina.css" type="text/css" media="all" />';
		$output .= '<link rel="stylesheet" href="css/shortcodes.css" type="text/css" media="all" />';
		$output .= '<link rel="stylesheet" href="css/settings.css" type="text/css" media="all" />';
		$output .= '<link rel="stylesheet"  href="css/captions.css" type="text/css" media="all" />';
		$output .= '<link rel="stylesheet"  href="css/color-variations/blue.css" type="text/css" media="all" title="blue"/>';
		$output .= '<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans" type="text/css" media="screen" />';
		$output .= '<script type="text/javascript" src="js/jquery.js"></script>';
		$output .= '<script type="text/javascript" src="js/jQuerytools.js"></script>';
		$output .= '<script type="text/javascript" src="js/utils.js"></script>';
		$output .= '<script type="text/javascript" src="js/zap.js"></script>';
		$output .= '<script type="text/javascript" src="js/blog.js"></script>';
		$output .= '<script type="text/javascript" src="js/camera.min.js"></script>';
		$output .= '<script type="text/javascript" src="js/layerslider.kreaturamedia.jquery.js"></script>';
		$output .= '<script type="text/javascript" src="js/jquery-easing-1.3.js"></script>';
		$output .= '<script type="text/javascript" src="js/jquerytransit.js"></script>';
		$output .= '<script type="text/javascript" src="js/layerslider.transitions.js"></script>';
		$output .= '<script type="text/javascript" src="js/jquery.themepunch.revolution.min.js"></script>';
		$output .= '<script type="text/javascript" src="js/jquery.flexslider-min.js"></script>	';
		$output .= '<script type="text/javascript" src="js/jflickrfeed.js"></script>';
		$output .= '<script type="text/javascript" src="js/jquery.jcarousel.min.js"></script>';
		$output .= '<script type="text/javascript" src="js/preview.js"></script>';
		$output .= '<script type="text/javascript" src="js/custom.js"></script>';
		return $output;
	}
	
}




 ?>